version: '3.8'

services: 
  dotnet:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: dotnet-dev
    tty: true
    stdin_open: true
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 5000:5000
